# -*- coding: utf-8 -*-
"""notebook_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sDSwo6l1oBhs0wkDlykeOhjV-y7nAhNq
"""

import os, glob
from IPython.display import Image, display

from IPython import display as ipython_display

ipython_display.clear_output()

!nvidia-smi

HOME=os.getcwd()

print(HOME)

!pip install ultralytics

import ultralytics

ultralytics.checks()

!mkdir {HOME}/folders

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/folders

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="api_key")
project = rf.workspace("").project("")
version = project.version(1)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

# Commented out IPython magic to ensure Python compatibility.
# %cd {dataset.location}

# Run

!yolo task=detect mode=train model=yolov10n.pt data='/content/folders/BuildingCracks-1/data.yaml' epochs=50 imgsz=640 amp=False

!yolo task=detect mode=val model=runs/detect/train/weights/best.pt data='/content/folders/BuildingCracks-1/data.yaml'

!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt source="/imgs1.jpg"


# CONVERSION SCRIPTS

!pip install onnx onnxruntime onnxconverter-common -q

from ultralytics import YOLO

# Load your trained FP32 model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Export to ONNX with FP16 quantization applied
model.export(
    format="onnx",     # format conversion → produces best.onnx
    half=True,         # quantization → FP16 applied during export
    imgsz=640,
    dynamic=False
)

print("Conversion done!")
#print("Output file: runs/detect/crack_yolov10n_fp32/weights/best.onnx")

#optional

import os

fp32_path = "runs/detect/train/weights/best.pt"
fp16_path = "runs/detect/train/weights/best.onnx"

fp32_size = os.path.getsize(fp32_path) / 1e6
fp16_size = os.path.getsize(fp16_path) / 1e6

print(f"FP32 model size: {fp32_size:.2f} MB")
print(f"FP16 ONNX size:  {fp16_size:.2f} MB")
print(f"Size reduction:  {((fp32_size - fp16_size)/fp32_size)*100:.1f}%")

from ultralytics import YOLO

# Load the ONNX model directly
onnx_model = YOLO("runs/detect/train/weights/best.onnx")

# Run validation — this gives your Quantized mAP50-95
metrics = onnx_model.val(data=f"/content/folders/BuildingCracks-1/data.yaml")

print(f"Quantized mAP50:    {metrics.box.map50:.4f}")
print(f"Quantized mAP50-95: {metrics.box.map:.4f}")
